name       : megaglest
version    : 3.13.0
release    : 5
source     :
    - git|https://github.com/MegaGlest/megaglest-source : 3.13.0
license    : GPL-2.0
component  : games.strategy
summary    : An open source cross-platform 3D real-time strategy game
description: |
    An open source cross-platform 3D real-time strategy game
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(fribidi)
    - pkgconfig(ftgl)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(icu-i18n)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libvlc)
    - pkgconfig(lua-5.3)
    - pkgconfig(ogg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - pkgconfig(x11)
    - pkgconfig(xerces-c)
    - libjpeg-turbo-devel
    - miniupnpc-devel
    - wxwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
