name       : megaglest
version    : 3.13.0
release    : 18
source     :
    - git|https://github.com/MegaGlest/megaglest-source : 3.13.0
license    : GPL-2.0-or-later
component  : games.strategy
summary    : An open source cross-platform 3D real-time strategy game
description: |
    An open source cross-platform 3D real-time strategy game
builddeps  :
    - pkgconfig(com_err)
    - pkgconfig(fontconfig)
    - pkgconfig(fribidi)
    - pkgconfig(ftgl)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(icu-i18n)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(libcurl)
    - pkgconfig(libnghttp2)
    - pkgconfig(libpng)
    - pkgconfig(libssh2)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libvlc)
    - pkgconfig(lua-5.3)
    - pkgconfig(ogg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - pkgconfig(x11)
    - pkgconfig(xerces-c)
    - miniupnpc-devel
    - wxwidgets-devel
environment: |
    export CFLAGS="${CFLAGS} -fcommon"
    export LDFLAGS="${LDFLAGS},--allow-multiple-definition"
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
